name: "Count bundles"
description: "Counts the number of bundle links in a comment body"
inputs:
  body:
    description: "The comment body"
    required: true
outputs:
  count:
    description: "Count of found bundles"
    value: "${{ steps.check.outputs.count }}"
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v5
      with:
        script: |
          console.log("ENV", process.env);

          let comment = core.getInput("body");
          console.log("comment", comment);

          const bundleRegex = /\[(octoprint-systeminfo-\d{14}\.zip)\]\(([^)]+)\)/g;
          const matches = comment.matchAll(bundleRegex);

          core.exportVariable("BUNDLE_COUNT", matches.length);
    - run: |
        echo "::set-output name=count::$BUNDLE_COUNT"
      id: check
      shell: bash
