name: "Count bundles"
description: "Counts the number of bundle links in a comment body"
inputs:
  body:
    description: "The comment body"
    required: true
outputs:
  count:
    description: "Count of found bundles"
    value: "${{ steps.check.outputs.count }}"
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v5
      env:
        BODY: "${{ inputs.body }}"
      with:
        script: |
          const { BODY } = process.env;
          console.log("comment", BODY);

          const bundleRegex = /\[(octoprint-systeminfo-\d{14}\.zip)\]\(([^)]+)\)/g;
          const matches = BODY.matchAll(bundleRegex);

          core.exportVariable("BUNDLE_COUNT", matches.length);
    - run: |
        echo "count=${{ env.BUNDLE_COUNT }}" >> $GITHUB_OUTPUT
      id: check
      shell: bash
