name: "Check for bundle"
description: "Checks a comment body whether it contains at least one systeminfo bundle"
inputs:
  body:
    description: "The comment body"
    required: true
outputs:
  result:
    description: "true if at least one uploaded bundle is present, false otherwise"
    value: "${{ env.CHECK_BUNDLE_RESULT }}"
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v2
      id: check
      with:
        script: |
          console.log("ENV", process.env);

          let comment = core.getInput("body");
          console.log("comment", comment);

          const bundleRegex = /\[(octoprint-systeminfo-\d{14}\.zip)\]\(([^)]+)\)/g;
          const matches = comment.matchAll(bundleRegex);

          core.setExportVariable("CHECK_BUNDLE_RESULT", matches.length > 0);
