name: "Comment or delete"
description: "Adds a comment to an issue or deletes it based on a provided condition"
inputs:
  issue:
    description: "The issue id"
    required: true
  marker:
    description: "The comment marker"
    default: ""
    required: true
  body:
    description: "The comment body"
    required: true
  condition:
    description: "The condition to evaluate"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const marker = core.getInput("marker");
          const body = core.getInput("body");
          const condition = core.getInput("condition");
          const issue = core.getIntput("issue");

          github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue,
          }).then(function(comments) {
            const comment = comments.data.find(c => c.user.login === "github-actions" && c.body.includes(marker));

            if (condition) {
              // condition evaluates true, we need to add or update a comment

              if (comment) {
                // update
                github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: comment.id,
                  body: body
                });
              } else {
                // add
                github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue,
                  body: body
                });
              }

            } else if (comment) {
              // condition evaluates false but there's a comment, we need to delete the comment

              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id
              });
            }
          });
