name: "Process Systeminfo Bundles"
description: "Process OctoPrint Systeminfo Bundles linked in issue comments and adds summaries and bundleviewer links for them as footnotes"

branding:
  icon: "package"
  color: "green"

inputs:
  github-token:
    description: GitHub token
    required: true
  repo:
    description: Repo on which the comment was made, in the format owner/name
    required: true
  comment:
    description: Comment ID, either this or the issue number need to be set
  issue:
    description: Issue number, either this or the comment id need to be set
  body:
    description: Text body - if not provided will be fetched via API

outputs:
  count:
    description: Number of detected bundles

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    TOKEN: ${{ inputs.github-token }}
    REPO: ${{ inputs.repo }}
    COMMENT: ${{ inputs.comment }}
    ISSUE: ${{ inputs.issue }}
    BODY: ${{ inputs.body }}
