name: "Create rpi-imager.json snippet"
description: "Generates an rpi-imager.json snippet based on given checksums, sizes and metadata"
inputs:
  name:
    description: "The name of the distribution"
    required: true
  description:
    description: "The description of the distribution"
    required: true
  icon:
    description: "The icon of the distribution"
    required: true
  url:
    description: "The download URL for the image zip"
    required: true
  output:
    description: "The path to the rpi-imager.json file"
    required: true
  image_sha256:
    description: "The sha256 checksum of the image"
    required: true
  image_size:
    description: "The size of the image"
    required: true
  zip_sha256:
    description: "The sha256 checksum of the zip"
    required: true
  zip_size:
    description: "The size of the zip"
    required: true
  devices:
    description: "Which Pis this image supports, comma separated, will be left out if not provided"
  init_format:
    description: "The init format of the image, defaults to systemd"
runs:
  using: "composite"
  steps:
    - name: "🆕 Create rpi-imager.json snippet"
      run: |
        IMAGE_SHA256="${INPUTS_IMAGE_SHA256}"
        IMAGE_SIZE=${INPUTS_IMAGE_SIZE}
        ZIP_SHA256="${INPUTS_ZIP_SHA256}"
        ZIP_SIZE=${INPUTS_ZIP_SIZE}
        OUTPUT="${INPUTS_OUTPUT}"

        NAME="${INPUTS_NAME}"
        DESCRIPTION="${INPUTS_DESCRIPTION}"
        ICON="${INPUTS_ICON}"
        URL="${INPUTS_URL}"
        DATE=`date '+%Y-%m-%d'`

        INIT_FORMAT="${INPUTS_INIT_FORMAT}"
        DEVICES_RAW="${INPUTS_DEVICES}"

        if [ -z "$INIT_FORMAT" ]; then
          INIT_FORMAT="systemd"
        fi

        IFS=', ' read -r -a DEVICES_ARR <<< "$DEVICES_RAW"
        DEVICES=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${DEVICES_ARR[@]}")

        cat > "$OUTPUT" <<EOF
        {
          "name": "$NAME",
          "description": "$DESCRIPTION",
          "url": "$URL",
          "icon": "$ICON",
          "release_date": "$DATE",
          "extract_size": $IMAGE_SIZE,
          "extract_sha256": "$IMAGE_SHA256",
          "image_download_size": $ZIP_SIZE,
          "image_download_sha256": "$ZIP_SHA256",
        EOF

        if [ -n "$DEVICES_RAW" ]; then
          cat >> "$OUTPUT" <<EOF
            "devices": $DEVICES,
        EOF
        fi

        cat >> "$OUTPUT" <<EOF
          "init_format": "$INIT_FORMAT"
        }
        EOF
      shell: bash
      env:
        INPUTS_IMAGE_SHA256: ${{ inputs.image_sha256 }}
        INPUTS_IMAGE_SIZE: ${{ inputs.image_size }}
        INPUTS_ZIP_SHA256: ${{ inputs.zip_sha256 }}
        INPUTS_ZIP_SIZE: ${{ inputs.zip_size }}
        INPUTS_OUTPUT: ${{ inputs.output }}
        INPUTS_NAME: ${{ inputs.name }}
        INPUTS_DESCRIPTION: ${{ inputs.description }}
        INPUTS_ICON: ${{ inputs.icon }}
        INPUTS_URL: ${{ inputs.url }}
        INPUTS_INIT_FORMAT: ${{ inputs.init_format }}
        INPUTS_DEVICES: ${{ inputs.devices }}
