name: 'PR Validator'
description: 'Runs some checks against incoming PRs'
author: 'foosel'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  query:
    description: 'The query to run'
  comment:
    description: 'A comment to add upon closing'
    required: false
  dry-run:
    description: 'If set, no actual actions will be performed'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
