name: 'Close by query'
description: 'Closes issues by query with optional comment'
author: 'foosel'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  query:
    description: 'The query to run'
  comment:
    description: 'A comment to add upon closing'
    required: false
  dry-run:
    description: 'If set, no actual actions will be performed'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
