name: 'Issue Validator'
description: 'Runs some checks against incoming issues'
author: 'foosel'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the issue-validation config'
    default: '.github/issue-validation.yml'
    required: false
  dry-run:
    description: 'If set, no actions will be performed'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
