name: "Build Python Dist"
description: "Builds distribution files for a Python project"

inputs:
  artifact:
    description: "Name of the artifact under which to provide the build result"
    required: false
    default: dist

runs:
  using: "composite"
  steps:
    - name: ðŸ— Install build dependencies
      shell: bash
      run: |
        python -m pip install build twine --user
    - name: ðŸ”¨ Build a binary wheel & an sdist tarball
      shell: bash
      run: |
        python -m build .
    - name: ðŸ”Ž Check wheel and sdist with twine
      shell: bash
      run: |
        twine check --strict dist/*
    - name: ðŸ”¨ Build a source tarball
      id: srcball
      shell: bash
      run: |
        sdist=$(ls dist/*.tar.gz)
        echo "sdist=$sdist" >> $GITHUB_OUTPUT

        prefix=$(basename ${sdist%.tar.gz})
        echo "prefix=$prefix" >> $GITHUB_OUTPUT

        wheel=$(ls dist/$prefix*.whl)
        echo "wheel=$wheel" >> $GITHUB_OUTPUT

        source="dist/$prefix.source.tar.gz"
        echo "source=$source" >> $GITHUB_OUTPUT

        # create the source tarball
        git archive --prefix "$prefix/" HEAD --output "$source"

        # list the files
        tree dist
    - name: ðŸ”¨ Create sha512sums of dist files
      shell: bash
      run: |
        cd dist
        sha512sum *.whl *.tar.gz > sha512sums.txt

        cat sha512sums.txt
    - name: Generate report
      shell: bash
      run: |
        cat << EOF >> $GITHUB_STEP_SUMMARY
        ### Dist Build Result

        \`\`\`
        $(tree dist)
        \`\`\`

        <details>
        <summary>sdist contents</summary>

        \`\`\`
        $(tar -tvf ${{ steps.srcball.outputs.sdist }})
        \`\`\`

        </details>

        <details>
        <summary>wheel contents</summary>

        \`\`\`
        $(unzip -l ${{ steps.srcball.outputs.wheel }})
        \`\`\`

        </details>

        <details>
        <summary>source tarball contents</summary>

        \`\`\`
        $(tar -tvf ${{ steps.srcball.outputs.source }})
        \`\`\`

        </details>

        <details>
        <summary>SHA512 sums</summary>

        \`\`\`
        $(cat dist/sha512sums.txt)
        \`\`\`

        </details>
        EOF
    - name: â¬† Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: dist
