name: "Build Python Dist"
description: "Builds distribution files for a Python project"

inputs:
  artifact:
    description: "Name of the artifact under which to provide the build result"
    required: false
    default: dist

runs:
  using: "composite"
  steps:
    - name: 🏗 Install build dependencies
      run: |
        python -m pip install build twine --user
    - name: 🔨 Build a binary wheel & an sdist tarball
      run: |
        python -m build .
    - name: 🔎 Check wheel and sdist with twine
      run: |
        twine check --strict dist/*
    - name: 🔨 Build a source tarball
      run: |
        # find the sdist
        sdist=$(ls dist/*.tar.gz)

        # strip the suffix to get the prefix
        prefix=$(basename ${sdist%.tar.gz})

        # create the source tarball
        git archive --prefix $prefix/ HEAD --output dist/$prefix.source.tar.gz

        # list the files
        tree dist
    - name: 🔨 Create sha512sums of dist files
      run: |
        cd dist
        sha512sum *.whl *.tar.gz > sha512sums.txt

        cat sha512sums.txt
    - name: ⬆ Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: dist
